### ISSUE TITLE
create heroku account

### ISSUE THREAD

**Issue by tariapper** [tariapper/reminder-webapp#15]
**Acceptance Test**

*Test 1*
1) Verify that everyone has a Heroku account that has read/write permission to the same project

**Comment by tariapper** [comment]
**Acceptance Test**

*Test 1*
1) Verify that everyone has a Heroku account that has read/write permission to the same project

**Comment by ahsanjkhan** [comment]
done creating mine

**Comment by KurtSu** [comment]
done
